trajectory: "input/traj/exampleTraj.lammpstrj"
variables: "example_lua/iceNanotube/strictCriterion/iceType/vars.lua"
bulk:
  use: false
  topologicalNetworkCriterion: false
  bondOrderParameters: false
topoOneDim:
  use: true
topoTwoDim:
  use: false