trajectory: "input/traj/mW_cubic.lammpstrj"
variables: "example_lua/fennel/vars.lua"
bulk:
  use: false
  topologicalNetworkCriterion: false
  bondOrderParameters: false
topoOneDim:
  use: false
topoTwoDim:
  use: false
structureDesc:
  use: true
