trajectory: "input/traj/tiny-selectionTest.lammpstrj"
variables: "example_lua/selection/tiny-selection/iceType/vars.lua"
bulk:
  use: true
  topologicalNetworkCriterion: false
  bondOrderParameters: false
topoOneDim:
  use: false
topoTwoDim:
  use: false