//-----------------------------------------------------------------------------------
// d-SEAMS - Deferred Structural Elucidation Analysis for Molecular Simulations
//
// Copyright (c) 2018--present d-SEAMS core team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the MIT License as published by
// the Open Source Initiative.
//
// A copy of the MIT License is included in the LICENSE file of this repository.
// You should have received a copy of the MIT License along with this program.
// If not, see <https://opensource.org/licenses/MIT>.
//-----------------------------------------------------------------------------------

#include <algorithm>
#include <generic.hpp>
#include <seams_input.hpp>

namespace {
/**
 * @details Record the ID-to-index entry for the most recently appended point.
 *  A duplicate atom ID means the input is corrupt (two atoms cannot share an
 *  ID within one frame); the map can only keep one of the colliding atoms, so
 *  name the ID loudly instead of failing silently downstream.
 */
void mapAtomIdToIndex(
    molSys::PointCloud<molSys::Point<double>, double> &yCloud) {
  const int idx = static_cast<int>(yCloud.pts.size()) - 1;
  const int id = yCloud.pts.back().atomID;
  if (!yCloud.idIndexMap.emplace(id, idx).second) {
    std::cerr << "Warning: duplicate atom ID " << id
              << " in the input frame; the ID-to-index map keeps only the "
                 "last atom read with this ID\n";
    yCloud.idIndexMap[id] = idx;
  }
}
} // namespace

/**
 * @details Get all the ring information, from the R.I.N.G.S. file. Each line
 * contains the IDs of the atoms in the ring. This is saved inside a vector of
 * vectors. Rings which have more than three consecutive water molecules are
 * discarded.
 */
std::vector<std::vector<int>> sinp::readBonds(std::string filename) {
  std::unique_ptr<std::ifstream> inpFile;
  inpFile = std::make_unique<std::ifstream>(filename);
  std::vector<std::vector<int>> bonds;
  std::string line;                // Current line being read in
  std::vector<std::string> tokens; // Vector containing word tokens
  std::vector<int> id;             // Vector for the IDs in the ring

  if (!(gen::file_exists(filename))) {
    std::cout << "Fatal Error: The bond file does not exist or you gave the "
                 "wrong path.\n";
    // Throw exception?
    return bonds;
  }

  // Format of the file:
  // 481 Bonds
  // 272    214    906   1361    388      1
  // 388   1361   1042   1548    237      1
  // 272   1536   1582   1701   1905      1

  if (inpFile->is_open()) {
    // ----------------------------------------------------------
    // At this point we know that the file is open
    std::getline((*inpFile), line); // Read in bonds
    // Run this until EOF or you reach the next timestep
    while (std::getline((*inpFile), line)) {
      // Read in lines and tokenize them into std::string words
      tokens = gen::tokenizer(line);

      id.clear();

      for (int i = 0; i < tokens.size(); i++) {
        id.push_back(std::stoi(tokens[i]));
      } // end of for, assigning values to id

      bonds.push_back(id);

    } // end of while, till EOF
    // ----------------------------------------------------------
  } // End of if file open statement

  inpFile->close();

  return bonds;
}
/**
 * @details Function for reading in an XYZ file
 */
molSys::PointCloud<molSys::Point<double>, double> sinp::readXYZ(std::string filename) {
  std::unique_ptr<std::ifstream> xyzFile;
  xyzFile = std::make_unique<std::ifstream>(filename);
  molSys::PointCloud<molSys::Point<double>, double>
      yCloud;
  std::string line;                // Current line being read in
  std::vector<std::string> tokens; // Vector containing word tokens
  std::vector<double> numbers;     // Vector containing type double numbers
  int nop = -1;                    // Number of atoms in targetFrame
  int iatom = 0;
  molSys::Point<double> iPoint; // Current point being read in from the file
  double xLo = 0.0, xHi = 0.0, yLo = 0.0, yHi = 0.0, zLo = 0.0, zHi = 0.0;

  if (!(gen::file_exists(filename))) {
    std::cout
        << "Fatal Error: The file does not exist or you gave the wrong path.\n";
    // Throw exception?
        throw std::runtime_error("Wrong filepath");
  }

  // --------
  // Before filling up the PointCloud, if the vectors are filled
  // empty them
  //yCloud = molSys::clearPointCloud(yCloud);
  // --------

  // Format of an XYZ file:
  //  1970
  // generated by VMD
  //  O         43.603500       16.926201       15.215700
  //  O         39.912601       14.775100       19.379200
  if (xyzFile->is_open()) {

    // ----------------------------------------------------------
    // At this point we know that the XYZ file is open

    // The first line contains the number of atoms
    std::getline((*xyzFile), line);
    nop = std::stoi(line);
    // Skip the comment line
    std::getline((*xyzFile), line);
    // Reserve memory for atom coordinates using nop read in
    yCloud.pts.reserve(nop);
    yCloud.nop = nop;
    // Run this until EOF or you reach the next timestep
    while (std::getline((*xyzFile), line)) {

      // Read in lines and tokenize them into std::string words and <double>
      // numbers
      tokens = gen::tokenizer(line);
      numbers = gen::tokenizerDouble(line);

      // Skip whitespace
      if (tokens.size() == 0) {
        continue;
      }

      // Put logic for checking atom type here later
      iPoint.type = 1; // Oxygen type; hard-coded!
      iPoint.x = std::stod(tokens[1]);
      iPoint.y = std::stod(tokens[2]);
      iPoint.z = std::stod(tokens[3]);
      if (yCloud.pts.empty()) {
        xLo = xHi = iPoint.x;
        yLo = yHi = iPoint.y;
        zLo = zHi = iPoint.z;
      } else {
        xLo = std::min(xLo, iPoint.x);
        xHi = std::max(xHi, iPoint.x);
        yLo = std::min(yLo, iPoint.y);
        yHi = std::max(yHi, iPoint.y);
        zLo = std::min(zLo, iPoint.z);
        zHi = std::max(zHi, iPoint.z);
      }
      iatom++;
      iPoint.molID = iatom;
      iPoint.atomID = iatom;
      yCloud.pts.push_back(iPoint);
      mapAtomIdToIndex(yCloud);
    } // end of while, looping through lines till EOF
    // ----------------------------------------------------------
  } // End of if file open statement

  xyzFile->close();

  if (yCloud.pts.size() == 1) {
    xHi = xLo + 10;
    yHi = yLo + 10;
    zHi = zLo + 10;
  } // for a single point in the system (never happens)

  yCloud.box = {xHi - xLo, yHi - yLo, zHi - zLo};
  yCloud.boxLow = {xLo, yLo, zLo};

  if (yCloud.pts.size() != yCloud.nop) {
    std::cout << "Atoms didn't get filled in properly.\n";
  }

  return yCloud;
}

// External Libraries

/**
 * @details  Function for reading in a lammps file. Reads in a specified frame
 *  (frame number and not timestep value).
 * @param[in] filename The name of the lammps trajectory file to be read in
 * @param[in] targetFrame The frame number whose information will be read in
 * @param[out] yCloud The outputted PointCloud
 * @param[in] isSlice This decides whether a slice will be created or not
 * @param[in] coordLow Contains the lower limits of the slice, if a slice is to
 *  be created
 * @param[in] coordHigh Contains the upper limits of the slice, if a slice is to
 *  be created
 */
molSys::PointCloud<molSys::Point<double>, double>
sinp::readLammpsTrj(std::string filename, int targetFrame,
                    molSys::PointCloud<molSys::Point<double>, double> &yCloud,
                    bool isSlice, std::array<double, 3> coordLow,
                    std::array<double, 3> coordHigh) {
  std::unique_ptr<std::ifstream> dumpFile;
  dumpFile = std::make_unique<std::ifstream>(filename);
  std::string line;                // Current line being read in
  std::vector<std::string> tokens; // Vector containing word tokens
  std::vector<double> numbers;     // Vector containing type double numbers
  std::vector<double> tilt;        // Vector containing tilt factors
  int currentFrame = 0;            // Current frame being read in
  int nop = -1;                    // Number of atoms in targetFrame
  bool foundFrame =
      false;            // Determines whether targetFrame has been found or not
  bool readNOP = false; // Flag for reading in the number of atoms
  bool readBox = false; // Flag for reading in the box lengths
  bool readAtoms = false; // Flag for reading in the atoms
  int xIndex, yIndex, zIndex,
      typeIndex;     // Indices for x,y,z coordinates, and LAMMPS type ID
  int molIndex = 0;  // Index for molecular ID
  int atomIndex = 0; // Index for atom ID (Only used if mol ID has not been set)
  molSys::Point<double> iPoint; // Current point being read in from the file
  xIndex = yIndex = zIndex = typeIndex = -1; // Default values
  bool isTriclinic = false; // Flag for an orthogonal or triclinic box

  if (!(gen::file_exists(filename))) {
    std::cout
        << "Fatal Error: The file does not exist or you gave the wrong path.\n";
    // Throw exception?
    return yCloud;
  }

  // The format of the LAMMPS trajectory file is:
  // ITEM: TIMESTEP
  // 0
  // ITEM: NUMBER OF ATOMS
  // 4096
  // ITEM: BOX BOUNDS pp pp pp
  // -7.9599900000000001e-01 5.0164000000000001e+01
  // -7.9599900000000001e-01 5.0164000000000001e+01
  // -7.9599900000000001e-01 5.0164000000000001e+01
  // ITEM: ATOMS id type x y z
  // 1 1 0 0 0 etc
  if (dumpFile->is_open()) {
    // ----------------------------------------------------------
    // At this point we know that the dumpfile is open
    // This loop searches for targetFrame
    while (std::getline((*dumpFile), line)) {
      // Read in lines and tokenize them
      tokens = gen::tokenizer(line);
      // Find out which timestep number
      // you are inside
      if (tokens[0].compare("ITEM:") == 0) {
        if (tokens[1].compare("TIMESTEP") == 0) {
          // Now you are in a new timestep. Update frame number
          currentFrame++;
        }
      }

      // If targetFrame has been found
      // break out of the while loop
      if (currentFrame == targetFrame) {
        foundFrame = true;
        break; // Exit the while loop
      }
    } // End of while loop searching for targetFrame
    // ----------------------------------------------------------
    // Before filling up the PointCloud, if the vectors are filled
    // empty them
    yCloud = molSys::clearPointCloud(yCloud);

    // ----------------------------------------------------------
    // If targetFrame has been found, read in the box lengths,
    // number of atoms and then read in atom positions, type, molID
    // By default, set molID=1 if not specified
    if (foundFrame) {
      // Run this until EOF or you reach the next timestep
      while (std::getline((*dumpFile), line)) {
        // Read in lines and tokenize them into std::string words and <double>
        // numbers
        tokens = gen::tokenizer(line);
        numbers = gen::tokenizerDouble(line);

        // If you've reached the timestep line then you've reached the
        // next frame. Break out of the while loop
        if (tokens[0].compare("ITEM:") == 0) {
          if (tokens[1].compare("TIMESTEP") == 0) {
            break;
          }
        }

        // -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
        // Read number of particles
        if (readNOP) {
          nop = std::stoi(line.data());
          readNOP = false;
          yCloud.pts.reserve(nop);
          yCloud.nop = nop;
        }
        // Read box lengths
        if (readBox) {
          // You've reached the end of box lengths
          if (tokens[0].compare("ITEM:") == 0) {
            readBox = false;
            // If the box is triclinic, get the
            // orthogonal 'bounding box'
            if (isTriclinic) {
              // Update tilt factors
              for (int k = 0; k < tilt.size(); k++) {
                yCloud.box.push_back(tilt[k]);
              }
            } // end of check for triclinic
          }
          // Or else fill up the box lengths
          else {
            yCloud.box.push_back(numbers[1] - numbers[0]); // Update box length
            yCloud.boxLow.push_back(
                numbers[0]); // Update the lower box coordinate
            // Do this for a triclinic box only
            if (numbers.size() == 3) {
              isTriclinic = true;
              tilt.push_back(numbers[2]);
            }
          }
        }
        // Read atoms into yCloud line by line
        if (readAtoms) {
          iPoint.type = numbers[typeIndex];
          iPoint.molID = numbers[molIndex];
          iPoint.atomID = numbers[atomIndex];
          iPoint.x = numbers[xIndex];
          iPoint.y = numbers[yIndex];
          iPoint.z = numbers[zIndex];
          // Check if the particle is inside the volume Slice
          // or not
          if (isSlice) { // only if a slice has been requested
            iPoint.inSlice = sinp::atomInSlice(iPoint.x, iPoint.y, iPoint.z,
                                               coordLow, coordHigh);
          }
          yCloud.pts.push_back(iPoint);
          mapAtomIdToIndex(yCloud);
        }
        // -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

        // Tests for reading in nop, box lengths, and atoms
        if (tokens[0].compare("ITEM:") == 0) {
          if (tokens[1].compare("NUMBER") == 0) {
            readNOP = true;
          }
        }
        if (tokens[0].compare("ITEM:") == 0) {
          if (tokens[1].compare("BOX") == 0) {
            readBox = true;
          }
        }
        if (tokens[0].compare("ITEM:") == 0) {
          if (tokens[1].compare("ATOMS") == 0) {
            readAtoms = true;
            // Now find out which index is the coordinate index etc
            for (int i = 2; i < tokens.size(); i++) {
              if (tokens[i].compare("type") == 0) {
                typeIndex = i - 2;
              }
              if (tokens[i].compare("x") == 0) {
                xIndex = i - 2;
              }
              if (tokens[i].compare("y") == 0) {
                yIndex = i - 2;
              }
              if (tokens[i].compare("z") == 0) {
                zIndex = i - 2;
              }
              if (tokens[i].compare("mol") == 0) {
                molIndex = i - 2;
              }
              if (tokens[i].compare("id") == 0) {
                atomIndex = i - 2;
              }
            } // End of for loop over tokens
            if (molIndex == 0) {
              molIndex = atomIndex;
            } // Set mol ID=atomID if not given
          }
        } // End of nested if loops for checking atom

      } // End of while
    }   // End of targetFrame found
    // ----------------------------------------------------------
  } // End of if file open statement

  // Check if you filled in the frame correctly
  if (!(foundFrame)) {
    std::cout << "You entered a frame that doesn't exist.\n";
  } // Throw exception
  if (foundFrame) {
    if (yCloud.pts.size() != yCloud.nop) {
      std::cout << "Atoms didn't get filled in properly.\n";
    }
  } // Throw exception
  yCloud.currentFrame = targetFrame;

  dumpFile->close();
  return yCloud;
}

/**
 * @details Function for reading in a lammps file; and saves only the Oxygen
 * atoms. This is an overloaded function. The Oxygen atom ID must be specified.
 * @param[in] filename The name of the lammps trajectory file to be read in
 * @param[in] targetFrame The frame number whose information will be read in
 * @param[out] yCloud The outputted PointCloud
 * @param[in] typeO The type ID of the Oxygen atoms
 * @param[in] isSlice This decides whether a slice will be created or not
 * @param[in] coordLow Contains the lower limits of the slice, if a slice is to
 *  be created
 * @param[in] coordHigh Contains the upper limits of the slice, if a slice is
 *  to be created
 */
molSys::PointCloud<molSys::Point<double>, double>
sinp::readLammpsTrjO(std::string filename, int targetFrame,
                     molSys::PointCloud<molSys::Point<double>, double> &yCloud,
                     int typeO, bool isSlice, std::array<double, 3> coordLow,
                     std::array<double, 3> coordHigh) {
  std::unique_ptr<std::ifstream> dumpFile;
  dumpFile = std::make_unique<std::ifstream>(filename);
  std::string line;                // Current line being read in
  std::vector<std::string> tokens; // Vector containing word tokens
  std::vector<double> numbers;     // Vector containing type double numbers
  std::vector<double> tilt;        // Vector containing tilt factors
  int currentFrame = 0;            // Current frame being read in
  int nop = -1;                    // Number of atoms in targetFrame
  bool foundFrame =
      false;            // Determines whether targetFrame has been found or not
  bool readNOP = false; // Flag for reading in the number of atoms
  bool readBox = false; // Flag for reading in the box lengths
  bool readAtoms = false; // Flag for reading in the atoms
  int xIndex, yIndex, zIndex,
      typeIndex;     // Indices for x,y,z coordinates, and LAMMPS type ID
  int molIndex = 0;  // Index for molecular ID
  int atomIndex = 0; // Index for atom ID (Only used if mol ID has not been set)
  molSys::Point<double> iPoint; // Current point being read in from the file
  xIndex = yIndex = zIndex = typeIndex = -1; // Default values
  bool isTriclinic = false; // Flag for an orthogonal or triclinic box
  int nOxy = 0;             // Number of oxygen atoms

  if (!(gen::file_exists(filename))) {
    std::cout
        << "Fatal Error: The file does not exist or you gave the wrong path.\n";
    // Throw exception?
    return yCloud;
  }

  // The format of the LAMMPS trajectory file is:
  // ITEM: TIMESTEP
  // 0
  // ITEM: NUMBER OF ATOMS
  // 4096
  // ITEM: BOX BOUNDS pp pp pp
  // -7.9599900000000001e-01 5.0164000000000001e+01
  // -7.9599900000000001e-01 5.0164000000000001e+01
  // -7.9599900000000001e-01 5.0164000000000001e+01
  // ITEM: ATOMS id type x y z
  // 1 1 0 0 0 etc
  if (dumpFile->is_open()) {
    // ----------------------------------------------------------
    // At this point we know that the dumpfile is open
    // This loop searches for targetFrame
    while (std::getline((*dumpFile), line)) {
      // Read in lines and tokenize them
      tokens = gen::tokenizer(line);
      // Find out which timestep number
      // you are inside
      if (tokens[0].compare("ITEM:") == 0) {
        if (tokens[1].compare("TIMESTEP") == 0) {
          // Now you are in a new timestep. Update frame number
          currentFrame++;
        }
      }

      // If targetFrame has been found
      // break out of the while loop
      if (currentFrame == targetFrame) {
        foundFrame = true;
        break; // Exit the while loop
      }
    } // End of while loop searching for targetFrame
    // ----------------------------------------------------------
    // Before filling up the PointCloud, if the vectors are filled
    // empty them
    yCloud = molSys::clearPointCloud(yCloud);

    // ----------------------------------------------------------
    // If targetFrame has been found, read in the box lengths,
    // number of atoms and then read in atom positions, type, molID
    // By default, set molID=1 if not specified
    if (foundFrame) {
      // Run this until EOF or you reach the next timestep
      while (std::getline((*dumpFile), line)) {
        // Read in lines and tokenize them into std::string words and <double>
        // numbers
        tokens = gen::tokenizer(line);
        numbers = gen::tokenizerDouble(line);

        // If you've reached the timestep line then you've reached the
        // next frame. Break out of the while loop
        if (tokens[0].compare("ITEM:") == 0) {
          if (tokens[1].compare("TIMESTEP") == 0) {
            break;
          }
        }

        // -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
        // Read number of particles
        if (readNOP) {
          nop = std::stoi(line.data());
          readNOP = false;
        }
        // Read box lengths
        if (readBox) {
          // You've reached the end of box lengths
          if (tokens[0].compare("ITEM:") == 0) {
            readBox = false;
            // If the box is triclinic, get the
            // orthogonal 'bounding box'
            if (isTriclinic) {
              // Update tilt factors
              for (int k = 0; k < tilt.size(); k++) {
                yCloud.box.push_back(tilt[k]);
              }
            } // end of check for triclinic
          }
          // Or else fill up the box lengths
          else {
            yCloud.box.push_back(numbers[1] - numbers[0]); // Update box length
            yCloud.boxLow.push_back(
                numbers[0]); // Update the lower box coordinate
            // Do this for a triclinic box only
            if (numbers.size() == 3) {
              isTriclinic = true;
              tilt.push_back(numbers[2]);
            }
          }
        }
        // Read atoms into yCloud line by line
        if (readAtoms) {
          iPoint.type = numbers[typeIndex];
          iPoint.molID = numbers[molIndex];
          iPoint.atomID = numbers[atomIndex];
          iPoint.x = numbers[xIndex];
          iPoint.y = numbers[yIndex];
          iPoint.z = numbers[zIndex];
          // Check if the particle is inside the volume Slice
          // or not
          if (isSlice) { // only if a slice has been requested
            iPoint.inSlice = sinp::atomInSlice(iPoint.x, iPoint.y, iPoint.z,
                                               coordLow, coordHigh);
          }
          // Save only oxygen atoms
          if (iPoint.type == typeO) {
            nOxy++;
            // yCloud.pts.resize(yCloud.pts.size()+1);
            yCloud.pts.push_back(iPoint);
            mapAtomIdToIndex(yCloud);
          }
        }
        // -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

        // Tests for reading in nop, box lengths, and atoms
        if (tokens[0].compare("ITEM:") == 0) {
          if (tokens[1].compare("NUMBER") == 0) {
            readNOP = true;
          }
        }
        if (tokens[0].compare("ITEM:") == 0) {
          if (tokens[1].compare("BOX") == 0) {
            readBox = true;
          }
        }
        if (tokens[0].compare("ITEM:") == 0) {
          if (tokens[1].compare("ATOMS") == 0) {
            readAtoms = true;
            // Now find out which index is the coordinate index etc
            for (int i = 2; i < tokens.size(); i++) {
              if (tokens[i].compare("type") == 0) {
                typeIndex = i - 2;
              }
              if (tokens[i].compare("x") == 0) {
                xIndex = i - 2;
              }
              if (tokens[i].compare("y") == 0) {
                yIndex = i - 2;
              }
              if (tokens[i].compare("z") == 0) {
                zIndex = i - 2;
              }
              if (tokens[i].compare("mol") == 0) {
                molIndex = i - 2;
              }
              if (tokens[i].compare("id") == 0) {
                atomIndex = i - 2;
              }
            } // End of for loop over tokens
            if (molIndex == 0) {
              molIndex = atomIndex;
            } // Set mol ID=atomID if not given
          }
        } // End of nested if loops for checking atom

      } // End of while
    }   // End of targetFrame found
    // ----------------------------------------------------------
  } // End of if file open statement

  // Check if you filled in the frame correctly
  if (!(foundFrame)) {
    std::cout << "You entered a frame that doesn't exist.\n";
  } // Throw exception
  if (foundFrame) {
    yCloud.nop = yCloud.pts.size();
    if (yCloud.pts.size() != nOxy) {
      std::cout << "Atoms didn't get filled in properly.\n";
    }
  } // Throw exception
  yCloud.currentFrame = targetFrame;

  dumpFile->close();
  return yCloud;
}

/**
 * @details Function for reading in a lammps file; and saves only the atoms of
 * the desired type. Atoms which are not inside the slice or not of type I are
 * not saved at all This is an overloaded function. The type atom ID must be
 *  specified.
 * @param[in] filename The name of the lammps trajectory file to be read in
 * @param[in] targetFrame The frame number whose information will be read in
 * @param[out] yCloud The outputted PointCloud
 * @param[in] typeI The type ID of the desired type of atoms
 * @param[in] isSlice This decides whether a slice will be created or not
 * @param[in] coordLow Contains the lower limits of the slice, if a slice is to
 *  be created
 *  @param[in] coordHigh Contains the upper limits of the slice, if a slice is
 *  to be created
 */
molSys::PointCloud<molSys::Point<double>, double> sinp::readLammpsTrjreduced(
    std::string filename, int targetFrame,
    molSys::PointCloud<molSys::Point<double>, double> &yCloud, int typeI,
    bool isSlice, std::array<double, 3> coordLow,
    std::array<double, 3> coordHigh) {
  std::unique_ptr<std::ifstream> dumpFile;
  dumpFile = std::make_unique<std::ifstream>(filename);
  std::string line;                // Current line being read in
  std::vector<std::string> tokens; // Vector containing word tokens
  std::vector<double> numbers;     // Vector containing type double numbers
  std::vector<double> tilt;        // Vector containing tilt factors
  int currentFrame = 0;            // Current frame being read in
  int nop = -1;                    // Number of atoms in targetFrame
  bool foundFrame =
      false;            // Determines whether targetFrame has been found or not
  bool readNOP = false; // Flag for reading in the number of atoms
  bool readBox = false; // Flag for reading in the box lengths
  bool readAtoms = false; // Flag for reading in the atoms
  int xIndex, yIndex, zIndex,
      typeIndex;     // Indices for x,y,z coordinates, and LAMMPS type ID
  int molIndex = 0;  // Index for molecular ID
  int atomIndex = 0; // Index for atom ID (Only used if mol ID has not been set)
  molSys::Point<double> iPoint; // Current point being read in from the file
  xIndex = yIndex = zIndex = typeIndex = -1; // Default values
  bool isTriclinic = false; // Flag for an orthogonal or triclinic box
  int nOxy = 0;             // Number of oxygen atoms

  if (!(gen::file_exists(filename))) {
    std::cout
        << "Fatal Error: The file does not exist or you gave the wrong path.\n";
    // Throw exception?
    return yCloud;
  }

  // The format of the LAMMPS trajectory file is:
  // ITEM: TIMESTEP
  // 0
  // ITEM: NUMBER OF ATOMS
  // 4096
  // ITEM: BOX BOUNDS pp pp pp
  // -7.9599900000000001e-01 5.0164000000000001e+01
  // -7.9599900000000001e-01 5.0164000000000001e+01
  // -7.9599900000000001e-01 5.0164000000000001e+01
  // ITEM: ATOMS id type x y z
  // 1 1 0 0 0 etc
  if (dumpFile->is_open()) {
    // ----------------------------------------------------------
    // At this point we know that the dumpfile is open
    // This loop searches for targetFrame
    while (std::getline((*dumpFile), line)) {
      // Read in lines and tokenize them
      tokens = gen::tokenizer(line);
      // Find out which timestep number
      // you are inside
      if (tokens[0].compare("ITEM:") == 0) {
        if (tokens[1].compare("TIMESTEP") == 0) {
          // Now you are in a new timestep. Update frame number
          currentFrame++;
        }
      }

      // If targetFrame has been found
      // break out of the while loop
      if (currentFrame == targetFrame) {
        foundFrame = true;
        break; // Exit the while loop
      }
    } // End of while loop searching for targetFrame
    // ----------------------------------------------------------
    // Before filling up the PointCloud, if the vectors are filled
    // empty them
    yCloud = molSys::clearPointCloud(yCloud);

    // ----------------------------------------------------------
    // If targetFrame has been found, read in the box lengths,
    // number of atoms and then read in atom positions, type, molID
    // By default, set molID=1 if not specified
    if (foundFrame) {
      // Run this until EOF or you reach the next timestep
      while (std::getline((*dumpFile), line)) {
        // Read in lines and tokenize them into std::string words and <double>
        // numbers
        tokens = gen::tokenizer(line);
        numbers = gen::tokenizerDouble(line);

        // If you've reached the timestep line then you've reached the
        // next frame. Break out of the while loop
        if (tokens[0].compare("ITEM:") == 0) {
          if (tokens[1].compare("TIMESTEP") == 0) {
            break;
          }
        }

        // -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
        // Read number of particles
        if (readNOP) {
          nop = std::stoi(line.data());
          readNOP = false;
        }
        // Read box lengths
        if (readBox) {
          // You've reached the end of box lengths
          if (tokens[0].compare("ITEM:") == 0) {
            readBox = false;
            // If the box is triclinic, get the
            // orthogonal 'bounding box'
            if (isTriclinic) {
              // Update tilt factors
              for (int k = 0; k < tilt.size(); k++) {
                yCloud.box.push_back(tilt[k]);
              }
            } // end of check for triclinic
          }
          // Or else fill up the box lengths
          else {
            yCloud.box.push_back(numbers[1] - numbers[0]); // Update box length
            yCloud.boxLow.push_back(
                numbers[0]); // Update the lower box coordinate
            // Do this for a triclinic box only
            if (numbers.size() == 3) {
              isTriclinic = true;
              tilt.push_back(numbers[2]);
            }
          }
        }
        // Read atoms into yCloud line by line
        if (readAtoms) {
          iPoint.type = numbers[typeIndex];
          iPoint.molID = numbers[molIndex];
          iPoint.atomID = numbers[atomIndex];
          iPoint.x = numbers[xIndex];
          iPoint.y = numbers[yIndex];
          iPoint.z = numbers[zIndex];
          // Check if the particle is inside the volume Slice
          // or not
          if (isSlice) { // only if a slice has been requested
            iPoint.inSlice = sinp::atomInSlice(iPoint.x, iPoint.y, iPoint.z,
                                               coordLow, coordHigh);
            // Skip if the atom is not part of the slice
            if (!iPoint.inSlice) {
              continue;
            } // do not save if not inside the slice
          }
          // Save only atoms of the desired type
          if (iPoint.type == typeI) {
            nOxy++;
            // yCloud.pts.resize(yCloud.pts.size()+1);
            yCloud.pts.push_back(iPoint);
            mapAtomIdToIndex(yCloud);
          }
        }
        // -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

        // Tests for reading in nop, box lengths, and atoms
        if (tokens[0].compare("ITEM:") == 0) {
          if (tokens[1].compare("NUMBER") == 0) {
            readNOP = true;
          }
        }
        if (tokens[0].compare("ITEM:") == 0) {
          if (tokens[1].compare("BOX") == 0) {
            readBox = true;
          }
        }
        if (tokens[0].compare("ITEM:") == 0) {
          if (tokens[1].compare("ATOMS") == 0) {
            readAtoms = true;
            // Now find out which index is the coordinate index etc
            for (int i = 2; i < tokens.size(); i++) {
              if (tokens[i].compare("type") == 0) {
                typeIndex = i - 2;
              }
              if (tokens[i].compare("x") == 0) {
                xIndex = i - 2;
              }
              if (tokens[i].compare("y") == 0) {
                yIndex = i - 2;
              }
              if (tokens[i].compare("z") == 0) {
                zIndex = i - 2;
              }
              if (tokens[i].compare("mol") == 0) {
                molIndex = i - 2;
              }
              if (tokens[i].compare("id") == 0) {
                atomIndex = i - 2;
              }
            } // End of for loop over tokens
            if (molIndex == 0) {
              molIndex = atomIndex;
            } // Set mol ID=atomID if not given
          }
        } // End of nested if loops for checking atom

      } // End of while
    }   // End of targetFrame found
    // ----------------------------------------------------------
  } // End of if file open statement

  // Check if you filled in the frame correctly
  if (!(foundFrame)) {
    std::cout << "You entered a frame that doesn't exist.\n";
  } // Throw exception

  // Update the number of particles
  yCloud.nop = yCloud.pts.size();

  // Update the frame number
  yCloud.currentFrame = targetFrame;

  dumpFile->close();
  return yCloud;
}

// ============================================================================
// Optional format readers (compiled only when dependencies are available)
// ============================================================================

#ifdef SEAMS_HAS_CHEMFILES
#include <chemfiles.hpp>

molSys::PointCloud<molSys::Point<double>, double>
sinp::readChemfiles(std::string filename, int targetFrame,
                    molSys::PointCloud<molSys::Point<double>, double> &yCloud,
                    int typeFilter) {
  try {
  chemfiles::Trajectory trajectory(filename);

  if (targetFrame < 1 ||
      static_cast<size_t>(targetFrame) > trajectory.nsteps()) {
    std::cerr << "Frame " << targetFrame << " does not exist in " << filename
              << " (has " << trajectory.nsteps() << " frames).\n";
    return yCloud;
  }

  yCloud = molSys::clearPointCloud(yCloud);

  auto frame = trajectory.read_step(static_cast<size_t>(targetFrame - 1));
  auto positions = frame.positions();
  auto cell = frame.cell();

  // Box dimensions
  yCloud.box = {cell.lengths()[0], cell.lengths()[1], cell.lengths()[2]};
  yCloud.boxLow = {0.0, 0.0, 0.0};

  auto &topology = frame.topology();

  for (size_t i = 0; i < frame.size(); i++) {
    // LAMMPS dumps carry numeric type identifiers, which chemfiles stores as
    // the atom type string with no atomic number; chemical formats carry
    // element names with an atomic number. Prefer a numeric type string,
    // fall back to the atomic number.
    const auto numeric = [](const std::string &s) {
      return !s.empty() &&
             s.find_first_not_of("0123456789") == std::string::npos;
    };
    int atomType = 0;
    if (numeric(topology[i].type())) {
      atomType = std::stoi(topology[i].type());
    } else if (numeric(topology[i].name())) {
      atomType = std::stoi(topology[i].name());
    } else {
      atomType = static_cast<int>(topology[i].atomic_number().value_or(1));
    }

    // Apply type filter if requested (-1 means accept all)
    if (typeFilter >= 0 && atomType != typeFilter) {
      continue;
    }

    molSys::Point<double> pt;
    pt.type = atomType;
    // chemfiles orders LAMMPS dump atoms by their id, so index + 1 recovers
    // the 1-based dump id for the contiguous case; other formats have no ID
    // notion beyond position
    pt.atomID = static_cast<int>(i) + 1;
    // Molecule IDs surface as chemfiles residues where the format has them
    const auto residue = topology.residue_for_atom(i);
    pt.molID = (residue && residue->id())
                   ? static_cast<int>(*residue->id())
                   : pt.atomID;
    pt.x = positions[i][0];
    pt.y = positions[i][1];
    pt.z = positions[i][2];

    yCloud.pts.push_back(pt);
    mapAtomIdToIndex(yCloud);
  }

  yCloud.nop = static_cast<int>(yCloud.pts.size());
  yCloud.currentFrame = targetFrame;

  return yCloud;
  } catch (const std::exception &e) {
    // chemfiles throws on unreadable or malformed files; report and return
    // the empty cloud instead of terminating the caller
    std::cerr << "chemfiles cannot read " << filename << ": " << e.what()
              << "\n";
    yCloud = molSys::clearPointCloud(yCloud);
    return yCloud;
  }
}
#endif // SEAMS_HAS_CHEMFILES

#ifdef SEAMS_HAS_READCON
// The C API rather than readcon-core.hpp: the C++ wrapper is a convenience
// layer over exactly these calls, and the C ABI is the surface cargo-c
// versions
#include <readcon-core.h>

molSys::PointCloud<molSys::Point<double>, double>
sinp::readCon(std::string filename, int targetFrame,
              molSys::PointCloud<molSys::Point<double>, double> &yCloud) {
  yCloud = molSys::clearPointCloud(yCloud);

  readcon::CConFrameIterator *frames =
      readcon::read_con_file_iterator(filename.c_str());
  if (frames == nullptr) {
    std::cerr << "Cannot open .con file " << filename << "\n";
    return yCloud;
  }

  int frameIdx = 0;
  while (readcon::RKRConFrame *handle =
             readcon::con_frame_iterator_next(frames)) {
    frameIdx++;
    if (frameIdx != targetFrame) {
      readcon::free_rkr_frame(handle);
      continue;
    }

    // Found the target frame; extract the transparent atom records
    readcon::CFrame *frame = readcon::rkr_frame_to_c_frame(handle);
    readcon::free_rkr_frame(handle);
    if (frame == nullptr) {
      std::cerr << "Cannot extract frame " << targetFrame << " from "
                << filename << "\n";
      break;
    }

    yCloud.box = {frame->cell[0], frame->cell[1], frame->cell[2]};
    yCloud.boxLow = {0.0, 0.0, 0.0};
    yCloud.pts.reserve(frame->num_atoms);

    for (size_t i = 0; i < frame->num_atoms; i++) {
      const readcon::CAtom &atom = frame->atoms[i];
      molSys::Point<double> pt;
      pt.type = static_cast<int>(atom.atomic_number);
      pt.atomID = static_cast<int>(atom.atom_id);
      pt.molID = pt.atomID;
      pt.x = atom.x;
      pt.y = atom.y;
      pt.z = atom.z;

      yCloud.pts.push_back(pt);
      mapAtomIdToIndex(yCloud);
    }
    readcon::free_c_frame(frame);

    yCloud.nop = static_cast<int>(yCloud.pts.size());
    yCloud.currentFrame = targetFrame;
    readcon::free_con_frame_iterator(frames);
    return yCloud;
  }

  if (yCloud.pts.empty()) {
    std::cerr << "Frame " << targetFrame << " not found in " << filename
              << " (has " << frameIdx << " frames).\n";
  }
  readcon::free_con_frame_iterator(frames);
  return yCloud;
}
#endif // SEAMS_HAS_READCON
