name: "Build d-SEAMS and test"
on: [push, pull_request]
jobs:
  build_pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          generate-run-shell: true
          environment-file: environment.yml
          cache-environment: true

      - name: Build application with cmake
        shell: micromamba-shell {0}
        run: |
          luarocks install luafilesystem
          mkdir bbdir
          cd bbdir
          export CXXFLAGS="-I$CONDA_PREFIX/include/eigen3 -I$CONDA_PREFIX/include/"
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=YES -DCMAKE_INSTALL_PREFIX:PATH=$CONDA_PREFIX ../
          make -j$(nproc)
          make install

      - name: Run a test
        shell: micromamba-shell {0}
        run: |
          $CONDA_PREFIX/bin/yodaStruct -c lua_inputs/config.yml
