name: "Build d-SEAMS API Docs"
on: [push, pull_request]
jobs:
  build_apidocs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: HaoZeke/doxyYoda@v0.1.1
      with:
        cppreference-tag: true
    - run: sudo apt-get install -y doxygen graphviz
    - run: doxygen Doxyfile-prj.cfg
    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: ./docs/html
    - name: Deploy Documentation
      if: ${{ github.ref == 'refs/heads/main' && github.repository == 'd-SEAMS/seams-core' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
