name: "Build d-SEAMS API Docs"
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_apidocs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: HaoZeke/doxyYoda@33bb2e287f333af6f4d6ad0e01b2539f4da0b9b9
      with:
        cppreference-tag: true
        version: 0.1.2
    - run: sudo apt-get install -y doxygen graphviz
    - run: doxygen Doxyfile-prj.cfg
    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: ./docs/html
    - name: Deploy Documentation
      if: ${{ github.ref == 'refs/heads/main' && github.repository == 'd-SEAMS/seams-core' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
