name: "[meson] test yodaLib, yodaStruct"
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Build library with meson
        shell: pixi run bash -e {0}
        run: |
          mkdir -p bbdir
          meson setup bbdir
          meson compile -C bbdir

  build_pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Test application with meson
        shell: pixi run bash -e {0}
        run: |
          mkdir -p bbdir
          meson setup bbdir -Dwith_lua=True \
                -Dwith_tests=True --prefix $CONDA_PREFIX
          meson install -C bbdir
          export LD_LIBRARY_PATH=$CONDA_PREFIX/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
          $CONDA_PREFIX/bin/yodaStruct -c lua_inputs/config.yml
